{
 "title": "SWIMMING POOL",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "iopool_temperature_measure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ORP",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    { "expr": "iopool_orp_measure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PH",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "iopool_ph_measure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Delta temperature -1h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_temperature_measure - iopool_temperature_measure offset 1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta temperature -12h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_temperature_measure - iopool_temperature_measure offset 12h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta temperature -24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_temperature_measure - iopool_temperature_measure offset 24h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta ORP -1h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_orp_measure - iopool_orp_measure offset 1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta ORP -12h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_orp_measure - iopool_orp_measure offset 12h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta ORP -24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_orp_measure - iopool_orp_measure offset 24h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta PH -1h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_ph_measure - iopool_ph_measure offset 1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta PH -12h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_ph_measure - iopool_ph_measure offset 12h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delta PH -24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iopool_ph_measure - iopool_ph_measure offset 2h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "iopool_temperature_measure", "legendFormat": "realtime" },
    {
     "expr": "iopool_temperature_measure offset 24h",
     "legendFormat": "time -24h"
    },
    {
     "expr": "count(ALERTS{alertname=~\"^Temperature.*\", alertstate=~\"(firing|pending)\"}) by (alertname, severity)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "ORP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    { "expr": "iopool_orp_measure", "legendFormat": "realtime" },
    { "expr": "iopool_orp_measure offset 24h", "legendFormat": "time -24h" },
    {
     "expr": "count(ALERTS{alertname=~\"^ORP.*\", alertstate=~\"(firing|pending)\"}) by (alertname, severity)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "PH",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "iopool_ph_measure", "legendFormat": "realtime" },
    { "expr": "iopool_ph_measure offset 24h", "legendFormat": "time -24h" },
    {
     "expr": "count(ALERTS{alertname=~\"^PH.*\", alertstate=~\"(firing|pending)\"}) by (alertname, severity)",
     "legendFormat": "{{alertname}}"
    }
   ]
  }
 ]
}