groups:
  - name: 'iopool-temperature'
    rules:
      - alert: 'TemperatureVeryHighSaturation'
        expr: 'iopool_temperature_measure >= 32'
        for: '10m'
        labels:
          severity: 'critical'
        annotations:
          summary: 'Temperature is very high'
      - alert: 'TemperatureMediumHighSaturation'
        expr: 'iopool_temperature_measure > 29 and iopool_temperature_measure < 32'
        for: '10m'
        labels:
          severity: 'warning'
        annotations:
          summary: 'Temperature is medium high'
      - alert: 'TemperatureMediumLowSaturation'
        expr: 'iopool_temperature_measure > 15 and iopool_temperature_measure < 20.5'
        for: '10m'
        labels:
          severity: 'warning'
        annotations:
          summary: 'Temperature is medium low'
      - alert: 'TemperatureVeryLowSaturation'
        expr: 'iopool_temperature_measure <= 15'
        for: '10m'
        labels:
          severity: 'critical'
        annotations:
          summary: 'Temperature is very low'
  - name: 'iopool-orp'
    rules:
      - alert: 'ORPVeryHighSaturation'
        expr: 'iopool_orp_measure >= 1000'
        for: '10m'
        labels:
          severity: 'critical'
        annotations:
          summary: 'ORP is very high'
      - alert: 'ORPMediumHighSaturation'
        expr: 'iopool_orp_measure > 800 and iopool_orp_measure < 1000'
        for: '10m'
        labels:
          severity: 'warning'
        annotations:
          summary: 'ORP is medium high'
      - alert: 'ORPMediumLowSaturation'
        expr: 'iopool_orp_measure > 550 and iopool_orp_measure < 650'
        for: '10m'
        labels:
          severity: 'warning'
        annotations:
          summary: 'ORP is medium low'
      - alert: 'ORPVeryLowSaturation'
        expr: 'iopool_orp_measure <= 550'
        for: '10m'
        labels:
          severity: 'critical'
        annotations:
          summary: 'ORP is very low'
  - name: 'iopool-ph'
    rules:
      - alert: 'PHVeryHighSaturation'
        expr: 'iopool_ph_measure >= 8.1'
        for: '10m'
        labels:
          severity: 'critical'
        annotations:
          summary: 'PH is very high'
      - alert: 'PHMediumHighSaturation'
        expr: 'iopool_ph_measure > 7.7 and iopool_ph_measure < 8.1'
        for: '10m'
        labels:
          severity: 'warning'
        annotations:
          summary: 'PH is medium high'
      - alert: 'PHMediumLowSaturation'
        expr: 'iopool_ph_measure > 6.8 and iopool_ph_measure < 7.1'
        for: '10m'
        labels:
          severity: 'warning'
        annotations:
          summary: 'PH is medium low'
      - alert: 'PHVeryLowSaturation'
        expr: 'iopool_ph_measure <= 6.8'
        for: '10m'
        labels:
          severity: 'critical'
        annotations:
          summary: 'PH is very low'
      